#!usr/bin/env python

import netfilterqueue
import scapy.all as scapy

def process_packet(packet):
    scapy_packet = scapy.IP(packet.get_payload())   #converting into scapy packet
    if scapy_packet.haslayer(scapy.DNSRR):   #checking for DNS response layer
       print(scapy_packet)
    packet.accept()  #to forward the packets

queue = netfilterqueue.NetfilterQueue()  #creating an instance of queue
queue.bind(0,process_packet)  #binding the queue and call back function
queue.run()